// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8bNw5Yr1qTjX3r8da8UF0TmY8xqf7lmM',
    appId: '1:206476989700:web:133efc7e2d5b0647336c51',
    messagingSenderId: '206476989700',
    projectId: 'vision-the-library',
    authDomain: 'vision-the-library.firebaseapp.com',
    storageBucket: 'vision-the-library.firebasestorage.app',
    measurementId: 'G-CQL8S7JHS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYxNZ-JRym7IadJC2332oIR1_u6X38ISw',
    appId: '1:206476989700:android:d50502c723a03c44336c51',
    messagingSenderId: '206476989700',
    projectId: 'vision-the-library',
    storageBucket: 'vision-the-library.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwBaemHNxZbTdc-000UErO2UGEgsohfDw',
    appId: '1:206476989700:ios:98a4c0d72e51ab0d336c51',
    messagingSenderId: '206476989700',
    projectId: 'vision-the-library',
    storageBucket: 'vision-the-library.firebasestorage.app',
    iosBundleId: 'com.example.visionTheLibraryNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwBaemHNxZbTdc-000UErO2UGEgsohfDw',
    appId: '1:206476989700:ios:98a4c0d72e51ab0d336c51',
    messagingSenderId: '206476989700',
    projectId: 'vision-the-library',
    storageBucket: 'vision-the-library.firebasestorage.app',
    iosBundleId: 'com.example.visionTheLibraryNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8bNw5Yr1qTjX3r8da8UF0TmY8xqf7lmM',
    appId: '1:206476989700:web:be5fdf2d917ca43c336c51',
    messagingSenderId: '206476989700',
    projectId: 'vision-the-library',
    authDomain: 'vision-the-library.firebaseapp.com',
    storageBucket: 'vision-the-library.firebasestorage.app',
    measurementId: 'G-2BTXCBKM7E',
  );
}
